pipeline {
  agent any
  tools {
    maven 'Maven3'   // 등록한 이름
    // jdk 'JDK17'  // JDK도 등록했다면 사용
  }
  stages {
    stage('Checkout'){ steps { checkout scm } }
    stage('Build'){
      steps { sh 'mvn -B clean package -DskipTests' }
    }
  }
}